# -*- coding: utf-8 -*-
"""gc_content_calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2RGAa1GR4-xs1SmHiL47VYUWbWsevHY
"""

def gc_content(dna):
  gc = dna.count('G') + dna.count('C')
  return (gc/len(dna))*100

sequence = "ATGTCTATCGGCAT"
print('GC content:', gc_content(sequence), '%')

DNA='ATGTCTAC'
reverse = DNA[::-1]
print('Reversed DNA:', reverse)

sequence = "ATGTCTATCGGCAT"
len(sequence)

from collections import Counter

sequence = "ATGTCTATCGGCAT"
counts = Counter(sequence)
print(counts)

