# -*- coding: utf-8 -*-
"""python-basics-practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OOWrFLi4ILK2Loy5XdHW92OX89MlslpO
"""

#My first Python program
name = "Roshan"
age = 23
weight = 90.9

print(name)
print(age)
print(weight)

print('My name is',(name))
print('My age is',age)
print('My current weight is',weight )

print('Hello World, My name is',name, 'and I am',age,'years old.')
print(f"My name is {name}, and I am {age} years old")

City = "Mumbai"
Temperature = "30"
print(f"I live in {City} and the temperature here is {Temperature}")

Name = "Mahek"
Age = '17'
City = 'Mumbai'
print(f"My name is {Name},I am {Age} years old and I live in {City}.")

name = 'Roshan'
age = 23
Weight = 90
is_fitness_goal_on = True

print(type(name))
print(type(age))
print(type(weight))
print(type(is_fitness_goal_on))

name = input("What is your name? ")
print(f"Hello, {name}!")

weight = float(input("Enter your weight in Kgs:"))
print(f"Your weight is {weight} in kgs")

Age = 20
if Age >= 18:
  print("You are an adult")
elif Age< 18:
  print("You are a minor")

Weight = float(input("Enter your weight in Kgs:"))
if Weight >= 90:
  print('Time to cut weight fatso')
elif Weight <= 70 and Weight <= 80:
  print('Still work on yourself')

